# Generated by Django 4.0 on 2022-12-24 09:44

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', tinymce.models.HTMLField(null=True)),
                ('image', models.ImageField(default='wes-hicks-4-EeTnaC1S4-unsplash.jpg', upload_to='profile_pics')),
                ('interests', models.ManyToManyField(blank=True, to='blog.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
